from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.units import cm
import json
from datetime import datetime
import os
import sys
import json

with open('data/flagged_zones.json') as f:
    zones = json.load(f)

# Get zone ID from argument or default to first
zone_id = int(sys.argv[1]) if len(sys.argv) > 1 else zones[0]['id']
zone = next(z for z in zones if z['id'] == zone_id)


output_path = f"data/report_zone_{zone['id']}.pdf"
doc = SimpleDocTemplate(output_path, pagesize=A4)
styles = getSampleStyleSheet()
story = []

# Title
title_style = ParagraphStyle('title', fontSize=20, fontName='Helvetica-Bold', textColor=colors.HexColor('#CC0000'))
story.append(Paragraph("AutoSentinel — Unauthorized Construction Report", title_style))
story.append(Spacer(1, 0.5*cm))

# Subtitle
story.append(Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}", styles['Normal']))
story.append(Paragraph("Area: Vasai Virar, Maharashtra | Period: 2019–2023", styles['Normal']))
story.append(Spacer(1, 0.5*cm))

# Severity badge
severity_color = {
    'CRITICAL': '#CC0000',
    'HIGH': '#FF6600',
    'MEDIUM': '#CCAA00',
    'LOW': '#006600'
}
sev_style = ParagraphStyle('sev', fontSize=14, fontName='Helvetica-Bold',
    textColor=colors.HexColor(severity_color[zone['severity']]))
story.append(Paragraph(f"Severity: {zone['severity']} | Risk Score: {zone['risk_score']}/100", sev_style))
story.append(Spacer(1, 0.5*cm))

# Zone details table
data = [
    ['Field', 'Value'],
    ['Zone ID', str(zone['id'])],
    ['Coordinates', f"{zone['lat']:.6f}, {zone['lon']:.6f}"],
    ['Area Detected', f"{zone['area_sqm']/10000:.2f} hectares ({zone['area_sqm']:,.0f} sqm)"],
    ['Severity Level', zone['severity']],
    ['Risk Score', f"{zone['risk_score']}/100"],
]

table = Table(data, colWidths=[6*cm, 10*cm])
table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#222222')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F5F5F5')),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#F5F5F5'), colors.white]),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('PADDING', (0, 0), (-1, -1), 8),
]))
story.append(table)
story.append(Spacer(1, 0.5*cm))

# Before/after images if they exist
before_path = f"data/images/zone_{zone['id']}_before.png"
after_path = f"data/images/zone_{zone['id']}_after.png"

if os.path.exists(before_path) and os.path.exists(after_path):
    story.append(Paragraph("Satellite Evidence", styles['Heading2']))
    img_before = Image(before_path, width=7*cm, height=7*cm)
    img_after = Image(after_path, width=7*cm, height=7*cm)
    img_table = Table([[img_before, img_after]])
    img_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    story.append(img_table)
    story.append(Paragraph("Left: 2019 (Before) | Right: 2023 (After)", styles['Normal']))
    story.append(Spacer(1, 0.5*cm))

# Recommended action
story.append(Paragraph("Recommended Action", styles['Heading2']))
story.append(Paragraph(zone['action'], styles['Normal']))
story.append(Spacer(1, 0.3*cm))
story.append(Paragraph(
    "This report is auto-generated by AutoSentinel for civic authority review. "
    "Flagged zones require ground verification before enforcement action.",
    styles['Italic']
))

doc.build(story)
print(f"Report saved to {output_path}")